[project]
name = "sso-jarvis-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "oci>=2.155.0",
    "playwright>=1.53.0",
    "requests>=2.32.4",
    "ruff>=0.12.1",
]
